### ISSUE TITLE
Problem with line_profiler

### ISSUE THREAD

**Issue by fbnrst** [barbagroup/numba_tutorial_scipy2016#4]
I cloned the repo and created a conda environment using the environment.yml file. I started to follow the tutorial. When I execute the cell 

``` python
%load_ext line_profiler
```

I get the following error:

``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-f2048e70c30c> in <module>()
----> 1 get_ipython().magic('load_ext line_profiler')

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-62> in load_ext(self, module_str)

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     35         if not module_str:
     36             raise UsageError('Missing module name.')
---> 37         res = self.shell.extension_manager.load_extension(module_str)
     38 
     39         if res == 'already loaded':

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     83                     __import__(module_str)
     84             mod = sys.modules[module_str]
---> 85             if self._call_load_ipython_extension(mod):
     86                 self.loaded.add(module_str)
     87             else:

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/IPython/core/extensions.py in _call_load_ipython_extension(self, mod)
    130     def _call_load_ipython_extension(self, mod):
    131         if hasattr(mod, 'load_ipython_extension'):
--> 132             mod.load_ipython_extension(self.shell)
    133             return True
    134 

/home/fabian/anaconda2/envs/numbatutorial/lib/python3.5/site-packages/line_profiler.py in load_ipython_extension(ip)
    370     """ API for IPython to recognize this module as an IPython extension.
    371     """
--> 372     ip.define_magic('lprun', magic_lprun)
    373 
    374 

AttributeError: 'ZMQInteractiveShell' object has no attribute 'define_magic'
```

**Comment by gforsyth** [comment]
Hey @fabianrost84 -- thanks for reporting!  There's a known issue with line_profiler and IPython 5.0.  There's a fix available but it hasn't been merged in yet.  For now, you can reinstall `line_profiler` using this command (which installs it from the fixed branch in the open PR)

``` bash
pip install --upgrade git+https://github.com/caethan/line_profiler
```

**Comment by fbnrst** [comment]
Thanks @gforsyth! Running `pip install --upgrade git+https://github.com/caethan/line_profiler` gave me the following error:

```
Collecting git+https://github.com/caethan/line_profiler
  Cloning https://github.com/caethan/line_profiler to /tmp/pip-f4gqa0vq-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-f4gqa0vq-build/setup.py", line 12, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-f4gqa0vq-build/setup.py", line 21, in <module>
        alternatively use a release tarball from PyPI to build it without Cython.""")
    distutils.errors.DistutilsError: You need Cython to build the line_profiler from a git ch
    alternatively use a release tarball from PyPI to build it without Cython.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-f4gqa0vq-build/
```

But that was simply fixed by

```
conda install cython
```

**Comment by gforsyth** [comment]
Great!  Glad it worked.
